use rmcp::{
    ErrorData as McpError, ServerHandler,
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::*,
    schemars, tool, tool_handler, tool_router,
};
use serde::Deserialize;
use serde_json::{Value, json};

use crate::peer::Peer;

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct TabIdParams {
    #[schemars(description = "Target tab ID (obtained from list_tabs).")]
    pub tab_id: i64,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct GetCookiesParams {
    #[schemars(description = "Target page URL; cookies for this URL's domain are returned.")]
    pub url: String,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct ExecuteScriptParams {
    #[schemars(
        description = "A function that runs inside the tab and returns its result; supports \
                       async. It receives the elements of `args` as its parameters."
    )]
    pub func_str: String,
    #[schemars(description = "Target tab ID (obtained from list_tabs).")]
    pub tab_id: i64,
    #[schemars(
        description = "Array of arguments passed to the function. For example, args=[1,2] calls \
                       func(1, 2)."
    )]
    #[serde(default)]
    pub args: Vec<Value>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct ExecuteTabToolParams {
    #[schemars(description = "Target tab ID (obtained from list_tabs).")]
    pub tab_id: i64,
    #[schemars(
        description = "Toolset ID from list_tab_tools. Required — never guess; names may repeat \
                       across toolsets."
    )]
    pub toolset_id: String,
    #[schemars(
        description = "Tool name from list_tab_tools. Required — never guess; discover at runtime."
    )]
    pub tool_name: String,
    #[schemars(
        description = "JSON object of arguments. Must match the tool's `inputSchema` from \
                       list_tab_tools. Pass `{}` when the tool takes no parameters."
    )]
    #[serde(default)]
    pub args: serde_json::Map<String, Value>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct ExecuteScriptInBackgroundParams {
    #[schemars(
        description = "A function that runs in the extension's background service worker and \
                       returns its result; supports async. It receives the elements of `args` as \
                       its parameters."
    )]
    pub func_str: String,
    #[schemars(
        description = "Array of arguments passed to the function. For example, args=[1,2] calls \
                       func(1, 2)."
    )]
    #[serde(default)]
    pub args: Vec<Value>,
}

#[derive(Clone)]
pub struct BrowserMcpServer {
    peer: Peer,
    #[allow(dead_code)]
    tool_router: ToolRouter<BrowserMcpServer>,
}

#[tool_router]
impl BrowserMcpServer {
    pub fn new(peer: Peer) -> Self {
        Self {
            peer,
            tool_router: Self::tool_router(),
        }
    }

    /// Tool metadata (name / description / input schema) generated by the
    /// `#[tool_router]` macro. Used by skill_setup to render SKILL.md so the
    /// installed skill stays in sync with the MCP server.
    pub fn tool_specs() -> Vec<rmcp::model::Tool> {
        Self::tool_router().list_all()
    }

    #[tool(
        description = "List every open tab in the browser. Returns each tab's id, title, active \
                       flag, last-accessed time, and URL. Use this to obtain tab_id before \
                       list_tab_tools, read_tab, execute_tab_tool, get_local_storage, etc."
    )]
    async fn list_tabs(&self) -> Result<CallToolResult, McpError> {
        self.call("list_tabs", json!({})).await
    }

    #[tool(
        description = "Read a condensed HTML snapshot of the given tab. Use list_tabs first to \
                       obtain its ID."
    )]
    async fn read_tab(
        &self,
        Parameters(p): Parameters<TabIdParams>,
    ) -> Result<CallToolResult, McpError> {
        self.call("read_tab", json!({ "tabId": p.tab_id })).await
    }

    #[tool(
        description = "Read a condensed HTML snapshot of the active tab in the current window. \
                       Use this when the user asks about \"the current page\" — no list_tabs \
                       needed first."
    )]
    async fn read_active_tab(&self) -> Result<CallToolResult, McpError> {
        self.call("read_active_tab", json!({})).await
    }

    #[tool(
        description = "Fetch the browser's cookies for the given URL's domain. Use this to access \
                       login-protected pages that aren't currently open in the browser: grab the \
                       cookies, then issue a plain HTTP request with them."
    )]
    async fn get_cookies(
        &self,
        Parameters(p): Parameters<GetCookiesParams>,
    ) -> Result<CallToolResult, McpError> {
        self.call("get_cookies", json!({ "url": p.url })).await
    }

    #[tool(
        description = "Fetch page errors from the given tab: JS exceptions, unhandled promise \
                       rejections, and CSP violations. Use this for debugging."
    )]
    async fn get_errors(
        &self,
        Parameters(p): Parameters<TabIdParams>,
    ) -> Result<CallToolResult, McpError> {
        self.call("get_errors", json!({ "tabId": p.tab_id }))
            .await
    }

    #[tool(
        description = "Run custom JavaScript inside the given tab. Use ONLY after list_tab_tools \
                       shows no matching page tool. For site-specific actions, prefer \
                       list_tab_tools + execute_tab_tool instead."
    )]
    async fn execute_script(
        &self,
        Parameters(p): Parameters<ExecuteScriptParams>,
    ) -> Result<CallToolResult, McpError> {
        self.call(
            "execute_script",
            json!({
                "tabId": p.tab_id,
                "funcStr": p.func_str,
                "args": p.args,
            }),
        )
        .await
    }

    #[tool(
        description = "List page tools available on the given tab. ALWAYS call this before \
                       execute_tab_tool or execute_script when the user wants to act on a web \
                       app. Returns toolset_id, tool_name, description, and inputSchema for each \
                       tool on that page (from subscribed toolsets or WebMCP — dynamic, varies by \
                       tab). Workflow: list_tabs → list_tab_tools → execute_tab_tool."
    )]
    async fn list_tab_tools(
        &self,
        Parameters(p): Parameters<TabIdParams>,
    ) -> Result<CallToolResult, McpError> {
        self.call("list_tab_tools", json!({ "tabId": p.tab_id }))
            .await
    }

    #[tool(
        description = "Invoke a page tool on the given tab. REQUIRED workflow: list_tabs to get \
                       tab_id → list_tab_tools to get toolset_id, tool_name, and inputSchema → \
                       call this with args matching inputSchema exactly. Do not guess tool_name \
                       or args — pick them from list_tab_tools. Prefer this over execute_script \
                       whenever list_tab_tools returns a matching tool."
    )]
    async fn execute_tab_tool(
        &self,
        Parameters(p): Parameters<ExecuteTabToolParams>,
    ) -> Result<CallToolResult, McpError> {
        self.call(
            "execute_tab_tool",
            json!({
                "tabId": p.tab_id,
                "toolsetId": p.toolset_id,
                "toolName": p.tool_name,
                "args": p.args,
            }),
        )
        .await
    }

    #[tool(
        description = "Run a JavaScript function in the extension's background service worker and \
                       return its result. Use this to open/close tabs and windows \
                       (chrome.tabs.create/remove, chrome.windows.create/remove), intercept \
                       network requests, control downloads, etc. Cannot quit the browser process \
                       itself. The full chrome.* API is available — async/await. Some APIs need \
                       optional permissions; call await chrome.permissions.request({ permissions: \
                       ['<name>'] }) first."
    )]
    async fn execute_script_in_background(
        &self,
        Parameters(p): Parameters<ExecuteScriptInBackgroundParams>,
    ) -> Result<CallToolResult, McpError> {
        self.call(
            "execute_script_in_background",
            json!({
                "funcStr": p.func_str,
                "args": p.args,
            }),
        )
        .await
    }

    #[tool(
        description = "Read the localStorage of the given tab (long values are truncated). Use \
                       this to inspect the page's locally persisted state."
    )]
    async fn get_local_storage(
        &self,
        Parameters(p): Parameters<TabIdParams>,
    ) -> Result<CallToolResult, McpError> {
        self.call("get_local_storage", json!({ "tabId": p.tab_id }))
            .await
    }

    #[tool(
        description = "Screenshot the given tab and return a base64-encoded PNG. Use list_tabs \
                       first to obtain its ID. The target tab is activated automatically so the \
                       screenshot succeeds."
    )]
    async fn screenshot_tab(
        &self,
        Parameters(p): Parameters<TabIdParams>,
    ) -> Result<CallToolResult, McpError> {
        let resp = match self
            .request_extension("screenshot_tab", json!({ "tabId": p.tab_id }))
            .await
        {
            Ok(resp) => resp,
            Err(msg) => return Ok(error_text_result(&msg)),
        };
        if let Some(image) = resp.get("image").and_then(|i| i.as_str()) {
            let format = resp.get("format").and_then(|f| f.as_str()).unwrap_or("png");
            return Ok(CallToolResult::success(vec![Content::image(
                image.to_string(),
                format!("image/{format}"),
            )]));
        }
        Ok(json_result(&resp))
    }
}

impl BrowserMcpServer {
    /// Send a request to the extension and convert the response into a
    /// CallToolResult. Failures (extension handler threw, timeout, peer
    /// disconnected) are returned as readable tool text so the LLM sees them.
    async fn call(&self, method: &str, params: Value) -> Result<CallToolResult, McpError> {
        match self.request_extension(method, params).await {
            Ok(resp) => Ok(json_result(&resp)),
            Err(msg) => Ok(error_text_result(&msg)),
        }
    }

    /// Send a request to the extension and wait for the response (30s timeout).
    async fn request_extension(&self, method: &str, params: Value) -> Result<Value, String> {
        match tokio::time::timeout(
            std::time::Duration::from_secs(30),
            self.peer.call(method, params),
        )
        .await
        {
            Ok(Ok(resp)) => Ok(resp),
            Ok(Err(err)) => Err(err.to_string()),
            Err(_) => Err("Timeout waiting for browser extension".to_string()),
        }
    }
}

fn error_text_result(msg: &str) -> CallToolResult {
    CallToolResult::success(vec![Content::text(format!("Error: {msg}"))])
}

fn json_result(value: &Value) -> CallToolResult {
    let json = serde_json::to_string_pretty(value).unwrap_or_else(|e| format!("Error: {e}"));
    CallToolResult::success(vec![Content::text(json)])
}

#[tool_handler]
impl ServerHandler for BrowserMcpServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::from_build_env())
            .with_instructions(
                "Control the user's active browser via this MCP server. Use this when built-in \
                 fetch/HTTP cannot access content (login walls, SSO, intranet), or when you need \
                 browser-specific data (cookies, localStorage, errors, screenshots) or web app \
                 interactions (forms, clicks, actions).\n\n**Workflow:** Use whichever tool fits. \
                 If you need to run JavaScript in a page (execute_script), call list_tab_tools \
                 first — if a tab tool can do the job, use execute_tab_tool instead (use \
                 toolset_id, tool_name, and inputSchema from list_tab_tools; never guess)."
                    .to_string(),
            )
    }
}
